### PR TITLE
Windows cp fix

### PR DESCRIPTION
**Pull request by icbat**
Tiny fix to help us windows folks =)

### CODE REVIEW

**Comment by julien** [comment]
Good catch, thanks

**Comment by julien** [comment]
For some reason I'm getting an error when trying to publish on npm 

Saying the 0.45.0 version already exists, I think I will keep updating `package.json` before publishing on next PRs

**Comment by icbat** [comment]
Sounds good, sorry for the hassle

**Comment by julien** [comment]
No worries ;)

**Comment by icbat** [comment]
Did #47 fix the issues you were seeing? I guess I just copied an older version from my project instead of the real, working one.

**Comment by julien** [comment]
no worries @icbat it's all ok :) i should have double checked too

**Pull request merged**
