### PR TITLE
State + prefab generaters, full demo game, bug fixes, slightly tweaked src/ file structure 

### PR DESCRIPTION
**Pull request by JTronLabs**
Thought this generator could use some prefab + state sub generators as well. These will allow the user to create files beyond what is initially needed to start a project, allowing a consistent dev environment for new files. Along the way I fixed some random bugs, tried to make things easier to understand, and added a more fleshed out game demo for n00bs.

### CODE REVIEW

**Comment by julien** [comment]
Hi @JTronLabs ,

First of all thanks a lot for your contribution it looks great.

Concerning the game, I'm all for it. In previous versions of the generator "the game" example was a bit less minimal in the way that it had graphics, but I was asked to remove it because people would usually generate the project and then removed the "boilerplate" code. I still think having a game example is a good idea because it helps getting familiar with Phaser. 

I'd really like the other committers and users to give use their opinion before merging in but I don't know if that will happen. 

I'm going to be a bit busy but if everything goes well, I'll merge this before the weekend.
Thanks again!

**Comment by JTronLabs** [comment]
@julien 

Thanks! I'm glad that you like it and want to incorporate it in. I was thinking that might be the case with the game, and I can try to scope it down a bit. 

I agree that something a bit more fleshed out would be a really big help for beginners. I wish that I had an example like this when I started, and even when I was making this I had to google a lot to remember/figure out how to do some things. 

I think that I'll try to reduce the images and thus overall package download size, and see if I can modularize the code more so it would be easier for more advanced users to delete the boilerplate. 

On the other hand, I could add an option to the original app generator: beginner (full game), advanced (minimal boilerplate) or something like that. Then have 2 folders in app/templates/es6 for the full/minimal game.

Thanks for your quick response, I'll try to get to this after work today but may end up being busy then & over the weekend. Really glad you like it though, first Open Source contribution :smile:

**Comment by GlennGeenen** [comment]
In my opinion adding an option to the generator asking for empty project or example project is the best solution, everybody happy !!!

**Comment by julien** [comment]
Hey guys, 

Totally agree with @GlennGeenen that would be awesome. 
I'll give you a shout as soon as I've tested and merged this.
And thanks again.

**Comment by JTronLabs** [comment]
@julien do you just want to wait till I add the option? It's no trouble to me to get it done, I'd prefer my contribution to be 'complete' when you merge.

**Comment by julien** [comment]
yes that would be great!

**Comment by JTronLabs** [comment]
Hey can I ask where I can read the docs on the  this.copy('assets/preloader.gif', 'assets/preloader.gif'); method? There has to be a copyDirectory function that we can use instead in app/index.js

**Comment by JTronLabs** [comment]
Nevermind, I found it: yeoman.io/authoring/file-system.html (under Legacy File Utilities). I'll update those too.

**Comment by JTronLabs** [comment]
Alright, I got it all fixed up and good to go. I also updated the README to provide more verbose instructions and background on what exactly this thing does. Good to merge?

**Comment by julien** [comment]
Great stuff, thanks again!
I just tested everything locally and everything is fine, there's just an error concerning
"assets/text_score_small.png" which gives a 404 - 
Do you want to "fix" this?

**Comment by JTronLabs** [comment]
I should've gotten it, just deleted a preload statement that got overlooked when I removed some assets.

**Comment by JTronLabs** [comment]
Actually, I noticed some more issues when I was testing it again. Let me fix those and we can merge on Monday. Sound good?

**Comment by julien** [comment]
Of course that's perfect

**Comment by JTronLabs** [comment]
Alright! Everything should be working fine now. Thanks for waiting.

**Comment by julien** [comment]
Thanks to you James

**Comment by JTronLabs** [comment]
Will this merge update the yeoman generator registered with NPM? Or are there additional steps to go thru? I've never published a yeoman generator.

**Comment by julien** [comment]
I guess so, it was published to npm

**Pull request merged**
